name: buck
description: An assembled flutter application framework Buck, Old longings nomadic leap, Chafing at custom's chain.
version: 0.1.4+1
authors:
  - leyan95 <leyansorosame@gmail.com>
homepage: https://github.com/leyan95/buck

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6
  dio: ^3.0.9
  flutter_local_notifications: ^1.4.0
  rxdart: ^0.24.0
  vibrate: ^0.0.4
  pda_scanner: ^0.2.6
  device_info: ^0.4.1+4
  fluttertoast: ^4.0.1
  open_file: ^3.0.0
  package_info: '>=0.4.0+13 <2.0.0'
  permission_handler: ^5.0.0+hotfix.6
  path_provider: ^1.6.5
  http_parser: ^3.1.3
  encrypt: ^4.0.0
  pointycastle: ^1.0.2
  flutter_spinkit: ^4.1.2
  device_sn: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: